// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package sts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FederationToken struct {
	AccessKey            string   `protobuf:"bytes,1,opt,name=AccessKey,proto3" json:"AccessKey,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	OriginalUser         string   `protobuf:"bytes,4,opt,name=OriginalUser,proto3" json:"OriginalUser,omitempty"`
	AllowAction          []string `protobuf:"bytes,5,rep,name=AllowAction,proto3" json:"AllowAction,omitempty"`
	AllowResource        []string `protobuf:"bytes,6,rep,name=AllowResource,proto3" json:"AllowResource,omitempty"`
	Expiration           string   `protobuf:"bytes,7,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FederationToken) Reset()         { *m = FederationToken{} }
func (m *FederationToken) String() string { return proto.CompactTextString(m) }
func (*FederationToken) ProtoMessage()    {}
func (*FederationToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *FederationToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FederationToken.Unmarshal(m, b)
}
func (m *FederationToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FederationToken.Marshal(b, m, deterministic)
}
func (m *FederationToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FederationToken.Merge(m, src)
}
func (m *FederationToken) XXX_Size() int {
	return xxx_messageInfo_FederationToken.Size(m)
}
func (m *FederationToken) XXX_DiscardUnknown() {
	xxx_messageInfo_FederationToken.DiscardUnknown(m)
}

var xxx_messageInfo_FederationToken proto.InternalMessageInfo

func (m *FederationToken) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *FederationToken) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *FederationToken) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FederationToken) GetOriginalUser() string {
	if m != nil {
		return m.OriginalUser
	}
	return ""
}

func (m *FederationToken) GetAllowAction() []string {
	if m != nil {
		return m.AllowAction
	}
	return nil
}

func (m *FederationToken) GetAllowResource() []string {
	if m != nil {
		return m.AllowResource
	}
	return nil
}

func (m *FederationToken) GetExpiration() string {
	if m != nil {
		return m.Expiration
	}
	return ""
}

func init() {
	proto.RegisterType((*FederationToken)(nil), "message.FederationToken")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xde, 0x32,
	0x72, 0xf1, 0xbb, 0xa5, 0xa6, 0xa4, 0x16, 0x25, 0x96, 0x64, 0xe6, 0xe7, 0x85, 0xe4, 0x67, 0xa7,
	0xe6, 0x09, 0xc9, 0x70, 0x71, 0x3a, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x7b, 0xa7, 0x56, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x40, 0xb2, 0xc1, 0xa9, 0xc9, 0x45, 0xa9, 0x25, 0x20,
	0x59, 0x26, 0x88, 0x2c, 0x5c, 0x40, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x19,
	0x2c, 0x01, 0x66, 0x0b, 0x29, 0x71, 0xf1, 0xf8, 0x17, 0x65, 0xa6, 0x67, 0xe6, 0x25, 0xe6, 0x84,
	0x16, 0xa7, 0x16, 0x49, 0xb0, 0x80, 0xe5, 0x50, 0xc4, 0x84, 0x14, 0xb8, 0xb8, 0x1d, 0x73, 0x72,
	0xf2, 0xcb, 0x1d, 0x93, 0x41, 0xee, 0x90, 0x60, 0x55, 0x60, 0xd6, 0xe0, 0x0c, 0x42, 0x16, 0x12,
	0x52, 0xe1, 0xe2, 0x05, 0x73, 0x83, 0x52, 0x8b, 0xf3, 0x4b, 0x8b, 0x92, 0x53, 0x25, 0xd8, 0xc0,
	0x6a, 0x50, 0x05, 0x85, 0xe4, 0xb8, 0xb8, 0x5c, 0x2b, 0x0a, 0x32, 0x21, 0xde, 0x91, 0x60, 0x07,
	0xdb, 0x84, 0x24, 0x92, 0xc4, 0x06, 0xf6, 0xbf, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x04,
	0xd6, 0xa6, 0x10, 0x01, 0x00, 0x00,
}
