package api

type Operation string

const (
	OpHeadObject              Operation = "HeadObject"
	OpCopyObjectPart          Operation = "CopyObjectPart"
	OpPutObjectPart           Operation = "PutObjectPart"
	OpListObjectParts         Operation = "ListObjectParts"
	OpCompleteMultipartUpload Operation = "CompleteMultipartUpload"
	OpNewMultipartUpload      Operation = "NewMultipartUpload"
	OpAbortMultipartUpload    Operation = "AbortMultipartUpload"
	OpCopyObject              Operation = "CopyObject"
	OpRenameObject            Operation = "RenameObject"
	OpRestoreObject           Operation = "RestoreObject"
	OpPutObjectAcl            Operation = "PutObjectAcl"
	OpGetObjectAcl            Operation = "GetObjectAcl"
	OpAppendObject            Operation = "AppendObject"
	OpPutObjectMeta           Operation = "PutObjectMeta"
	OpPutObject               Operation = "PutObject"
	OpPostObject              Operation = "PostObject"
	OpGetObject               Operation = "GetObject"
	OpDeleteObject            Operation = "DeleteObject"
	OpGetBucketLocation       Operation = "GetBucketLocation"
	OpListMultipartUploads    Operation = "ListMultipartUploads"
	OpGetBucketVersioning     Operation = "GetBucketVersioning"
	OpListVersionedObjects    Operation = "ListVersionedObjects"
	OpPutBucketAcl            Operation = "PutBucketAcl"
	OpGetBucketAcl            Operation = "GetBucketAcl"
	OpPutBucketVersioning     Operation = "PutBucketVersioning"
	OpPutBucketCors           Operation = "PutBucketCors"
	OpGetBucketCors           Operation = "GetBucketCors"
	OpDeleteBucketCors        Operation = "DeleteBucketCors"
	OpPutBucketLogging        Operation = "PutBucketLogging"
	OpGetBucketLogging        Operation = "GetBucketLogging"
	OpPutBucketLifeCycle      Operation = "PutBucketLifeCycle"
	OpGetBucketLifeCycle      Operation = "GetBucketLifeCycle"
	OpDelBucketLifeCycle      Operation = "DelBucketLifeCycle"
	OpPutBucketPolicy         Operation = "PutBucketPolicy"
	OpGetBucketPolicy         Operation = "GetBucketPolicy"
	OpDeleteBucketPolicy      Operation = "DeleteBucketPolicy"
	OpPutBucketWebsite        Operation = "PutBucketWebsite"
	OpGetBucketWebsite        Operation = "GetBucketWebsite"
	OpDeleteBucketWebsite     Operation = "DeleteBucketWebsite"
	OpPutBucketEncryption     Operation = "PutBucketEncryption"
	OpGetBucketEncryption     Operation = "GetBucketEncryption"
	OpDeleteBucketEncryption  Operation = "DeleteBucketEncryption"
	OpHeadBucket              Operation = "HeadBucket"
	OpDeleteMultipleObjects   Operation = "DeleteMultipleObjects"
	OpDeleteBucket            Operation = "DeleteBucket"
	OpPutBucket               Operation = "PutBucket"
	OpListObjects             Operation = "ListObjects"
	OpListBuckets             Operation = "ListBuckets"
)
